---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

Under the assumption that the target file is in the local
directory where the script is running the following code 
loads it into memory:

```{r: load the data, echo=TRUE}
defaultFileName <- "activity.csv"
if( !file.exists( file.path(defaultFileName))) {
    defaultFileName <- unzip( zipfile="activity.zip" )  
}
loaded_data <- suppressWarnings(read.csv(file = defaultFileName, 
                                 header=TRUE,
                                 quote='"',
                                 stringsAsFactors=FALSE,
                                 encoding="UTF-8"))
rm(defaultFileName)
```
The result is a data frame called `loaded_data`:

```{r: loaded data frame str, echo=FALSE}
str(loaded_data)
```
A few of the first, last, and some intermediate rows look as follows:
```{r: first and last rows, echo=FALSE}
head(loaded_data,n=3)
loaded_data[12308:12310,]
tail(loaded_data,n=3)
```
Before proceeding it is a good idea to transform the dates from strings 
into date format.
```{r: dates from strings to real date format, echo=TRUE}
clean_data <- loaded_data
clean_data$date <- as.Date(x= clean_data$date,format="%Y-%m-%d")
str(clean_data)
```

## What is mean total number of steps taken per day?

First a histogram of steps per day was generated with ggplot
`geom_bar`:

```{r:plot steps per day, cache=TRUE,echo=TRUE,fig.height=4,message=FALSE}
require(ggplot2)
## The data is already in the long format so ggplot can be used to generate the
## histogram
ggplot(data=clean_data, aes(x=date,y=steps)) +
    geom_bar(stat="identity") +
    labs(title="Number of steps per day") +
    labs(x= "Date", y= "Number of steps") 
```

Then the mean and median of the average number of steps per day
was computed from a transformation of the `steps`vector
of the `clean_data` data frame using the `mean` function
and the common date for each entry as the criterion for filtering
using the R function `tapply`.

```{r: compute steps per day,cache=FALSE, echo=TRUE}
count_steps_per_day <-tapply(X=clean_data$steps,INDEX=clean_data$date,sum)
```
Finally the mean and median of the steps per day are computed:

```{r: compute stats for steps per day,cache=FALSE,echo=TRUE,results='asis'}
mean_steps_per_day <- mean(count_steps_per_day, na.rm=TRUE)
median_steps_per_day <- median(count_steps_per_day, na.rm=TRUE)
```
The values are as follows:

```{r: print stats steps per day, cache=FALSE,echo=FALSE}
options(digits=2)
paste( "Mean steps per day  = " , mean_steps_per_day )
paste( "Median steps per day = ", median_steps_per_day )
# avoid side effects after this step
rm(count_steps_per_day,mean_steps_per_day, median_steps_per_day)
```

These values check with those plotted in the histogram according to visual
inspection of the y-axis values.

## What is the average daily activity pattern?

The original data frame has the running time in intervals of 5 minutes, expressed 
as hours and seconds from 0 to 2355 for each of the 61 days of data (31 in October and 30 in November).

I decided to convert those intervals to running minutes for each 24 hour period
(24*60/5=288 5-minute time markers) for 61 days. 
The following code creates a vector called `vector_minutes_for_61days` 
with these daily running 5-minute intervals from 0 to 1435. 
That vector will be used for plotting and extracting time for specific values of interest.

```{r: daily activity pattern,echo=TRUE,results='asis'}
vector_of_minutes_per_day <- (0:287)*5
vector_minutes_for_61days <- rep(x=vector_of_minutes_per_day, times=61)
```

Then a new vector with the mean number of steps reported at each of the time intervals
is created, the `NA` are removed:

```{r: daily activity part 2, echo=TRUE}
steps_per_interval<- tapply(X=clean_data$steps, 
                            vector_minutes_for_61days, 
                            FUN=mean,
                            na.rm=T,
                            simplify=TRUE)
```

Now the maximum value of average steps per 5-minute interval can be extracted directly:

```{r: max step interval, cache=TRUE, echo=FALSE, results='asis' }
hour_of_day_for_max_steps <- floor(as.numeric(names(which.max(x=steps_per_interval)))/60)
minutes_of_day_for_max_steps <- as.numeric(names(which.max(x=steps_per_interval))) %% 60
maxsteps<-round(x=max(steps_per_interval), digits=0)
paste0("max( steps_per_interval ) = ",
       maxsteps, 
       " steps")
```

From the vector of average steps per 5 minute intervals the time this maximum
happens during the day is computed at `r paste0(hour_of_day_for_max_steps,":",minutes_of_day_for_max_steps," a.m.")`.


```{r: preparing labels for plot, cache=TRUE, echo=FALSE}
## prepare labels  for x axis in this plot
lbls<- as.character(clean_data$interval[0:288])
insertColon <- function(l){
    nchars <- nchar(l)
    if( nchars < 2 ) {
        paste0("00:0",l)
    }
    else if ( nchars < 3 ) {
        paste0("00:", l)
    }
    else if( nchars < 4 ) {
        paste0("0", substr(l,1,1),":", substr(l,2,3) )
    }
    else if( nchars < 5 ) {
        paste0( substr(l,1,2), ":", substr(l,3,4))
    }
    else
        ""
}
prettylbls <- lapply(lbls,FUN=insertColon)
```

The series plot was generated with the following code:

```{r: plot activity pattern, cache=TRUE,echo=TRUE,fig.height=6}
plotStepDailyAverages <- function( v_of_steps_per_interval, title ) {
    plot(x=names(v_of_steps_per_interval),
         y=v_of_steps_per_interval, 
         xlab="Daily intervals, minutes:seconds", ylab="number of steps",
         main= title,
         type="l",
         ylim=c(-1,201),
         pch=7, axes=FALSE)
    Axis(side=1,
         at=vector_of_minutes_per_day[c(1,25,50,75,100,125,150,175,200,225,250,275,288)],
         labels= prettylbls[c(1,25,50,75,100,125,150,175,200,225,250,275,288)],
         col='blue', col.ticks = 'red', col.axis = 'blue',
         tck = 0.03, xaxs="r")
    Axis(side=3,
         at=vector_of_minutes_per_day[c(1,25,50,75,100,125,150,175,200,225,250,275,288)],
         labels= c("","","","","","","","","","","","",""),
         col = 'blue', col.ticks = 'red', col.axis = 'blue',
         las=2, tck = 1, # 100% of width or "grid lines on"
         lty= "dotted", xaxs="r")
    Axis(side=2,
         at=c(0,50,100,150,200),
         labels= c("0","50","100", "150", "200"),
         col='blue', col.ticks = 'red', col.axis = 'blue',
         tck = 0.03, xaxs="r")
    Axis(side=4,
         at=c(0,50,100,150,200),
         labels= c("","","", "", ""),     
         col = 'blue', col.ticks = 'red', col.axis = 'blue',
         las=2, tck = 1, # 100% of width or "grid lines on"
         lty="dotted", xaxs="r")
}
plotStepDailyAverages(steps_per_interval, "Activity pattern as steps per daily time interval")
```


## Imputing missing values

The number of days that contain `NA` can be computed with a table
over a logical vector testing for `NA` in the vector that
contains the count of the number of steps per day.

```{r: NA count, cache=TRUE,echo=TRUE}
count_steps_per_day <-tapply(X=clean_data$steps,INDEX=clean_data$date,sum)
table(is.na(count_steps_per_day))
```

There are 8 days that had `NA` data in them.

However the total number of actual `NA` readings can be computed with th following 
similar R code:

```{r: NA count steps total, cache=TRUE, echo=TRUE}
table(is.na(clean_data$steps))
```
So there are `r  table(is.na(clean_data$steps))[2][[1]]` `NA` entries in the `step`
column.

They can be filled in a number of ways:

    * with zero.
    * with the average number of steps per interval computed in the previous non-empty step.
    * with the average steps for the same time interval across all days.
    * with the average steps for the same weekday or weekend day.
    * with the average of the two non-empty neighbour intervals.

### Replazing `NA`s with zero

Let's try the first strategy:

```{r: nas with zeros, cache=FALSE, echo=TRUE}
# auxiliary functions:
replaceNAforValue <- function( vect, indx, val) {
    if ( is.na( vect ) )
        val
    else
        vect
}
prepareVecOfNewValues <- function( vect, initial_val) {
    f<-function(x_val) {
        if (is.na(x_val))
            initial_val
        else
            x_val
    }
    # build vector in one pass:
    sapply(X=vect,FUN=f)
}
# a vector of indexes
v_of_indx <-(row(clean_data))[,1]
# a vector of replacement values:
v_of_replacements <- prepareVecOfNewValues( clean_data$steps, as.numeric(0))

l_of_replacements_for_na <- Map( f=replaceNAforValue, # function to map
                              clean_data$steps, # vector of first arg to f 
                              v_of_indx,  # vector of second arg to f
                              v_of_replacements) # vector of third arg to f

v_of_zeros_for_nas <- unlist(l_of_replacements_for_na)
```

Now let's compute the new steps per interval activity:

```{r: activity nas as zeros, cache=FALSE,echo=TRUE}
steps_per_interval_nas_as_zero <- tapply(X=v_of_zeros_for_nas,
                                         vector_minutes_for_61days, 
                                         FUN=mean,
                                         na.rm=T,
                                         simplify=TRUE)
plotStepDailyAverages(steps_per_interval_nas_as_zero, "Activity pattern as steps per daily time interval, NAs as zero")
```

The effect is to lower the average because of the introduction of zeros.
Now the maximum number of steps per 5-minute interval is:

```{r: max steps with nas as zeros, echo=FALSE, results='asis'}
hour_of_day_for_max_steps <- floor(as.numeric(names(which.max(x=steps_per_interval_nas_as_zero)))/60)
minutes_of_day_for_max_steps <- as.numeric(names(which.max(x=steps_per_interval_nas_as_zero))) %% 60
maxsteps<-round(x=max(steps_per_interval_nas_as_zero), digits=0)
paste0("max( steps_per_interval_nas_as_zero ) = ",
       maxsteps, 
       " steps")
```

From this new vector of average steps per 5 minute intervals the time this maximum
happens during the day is computed at `r paste0(hour_of_day_for_max_steps,":",minutes_of_day_for_max_steps," a.m.")`,
so it does not change with respect to removing the `NA`s. The effect is only to scale down the 
results but it does not shift the time scale.


### Replacing `NA`s with the average steps for the same time interval across all days

Replacing the `NA`s for the average steps per 5-minute interval as computed above reverts to
the same curve because now the averages.

```{r: replacing NAs with averages, echo=TRUE}
prepareVecOfNewValuesAsAvg <- function( vect, avg) {
    f<-function(x_val, y_val) {
        if (is.na(x_val))
            y_val
        else
            x_val
    }
    # build vector in one pass:
    as.vector(mapply(FUN=f,vect,avg,SIMPLIFY=T))
}

avg_step_vect= rep(x=steps_per_interval,times=61)

v_of_replacements_avg <- prepareVecOfNewValuesAsAvg( clean_data$steps, avg_step_vect )


l_of_replacements_for_na_as_avg <- Map( f=replaceNAforValue, # function to map
                                 clean_data$steps, # vector of first arg to f 
                                 v_of_indx,  # vector of second arg to f
                                 v_of_replacements_avg) # vector of third arg to f

v_of_replacements_for_na_as_avg <- unlist(l_of_replacements_for_na_as_avg)

steps_per_interval_nas_as_avg <- tapply(X=v_of_replacements_for_na_as_avg,
                                         vector_minutes_for_61days, 
                                         FUN=mean,
                                         na.rm=T,
                                         simplify=TRUE)

plotStepDailyAverages(steps_per_interval_nas_as_avg, 
                      "Activity pattern as steps per daily time interval, NAs as average")
```

## Are there differences in activity patterns between weekdays and weekends?

```{r:weekday analysis, cache=TRUE}
clean_data$weekday_name <- weekdays(clean_data$date)

```
